apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillflight
  namespace: skillflight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skillflight
  template:
    metadata:
      labels:
        app: skillflight
    spec:
      containers:
      - name: skillflight
        image: noletengine/skillflight:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: skillflight-service
  namespace: skillflight
spec:
  selector:
    app: skillflight
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30046
