apiVersion: v1
kind: PersistentVolume
metadata:
  name: argocd-repo-server-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.144
    path: /nfs/argocd-repo
  persistentVolumeReclaimPolicy: Retain

