apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: argocd
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 32520
    - name: https
      port: 443
      targetPort: 8080
      protocol: TCP
      nodePort: 31260
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4

