apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mypersonal
  namespace: argocd
spec:
  destination:
    namespace: mypersonal
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/site-reliability/mypersom.git
    path: helm/mypersonal
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

