replicaCount: 1

image:
  repository: noletengine/skillflight
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 80
  nodePort: 30036

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

